"""add activity folder to ChannelBot

Revision ID: 2ee86904292b
Revises: 1e74bbac5a48
Create Date: 2023-09-29 20:58:15.337377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee86904292b'
down_revision = '1e74bbac5a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChannelBotBundles', sa.Column('active', sa.Boolean(), server_default='True'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChannelBotBundles', 'active')
    # ### end Alembic commands ###
