"""update ChanneBot

Revision ID: 954e45b68e8f
Revises: 9e6041f4cde4
Create Date: 2023-09-21 20:29:19.386484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954e45b68e8f'
down_revision = '9e6041f4cde4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChannelBotBundles', sa.Column('date_parsed', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChannelBotBundles', 'date_parsed')
    # ### end Alembic commands ###
