"""rename bots -> Bots

Revision ID: cb73fc9ef892
Revises: 6417171b537b
Create Date: 2023-09-22 16:02:57.411488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb73fc9ef892'
down_revision = '6417171b537b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('channels_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('bot_token'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('bots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bot_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('channels_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bots_pkey'),
    sa.UniqueConstraint('alias', name='bots_alias_key'),
    sa.UniqueConstraint('bot_token', name='bots_bot_token_key'),
    sa.UniqueConstraint('description', name='bots_description_key'),
    sa.UniqueConstraint('name', name='bots_name_key')
    )
    op.drop_table('Bots')
    # ### end Alembic commands ###
