"""add new User's model

Revision ID: de000d1ff208
Revises: 17a6548abde5
Create Date: 2023-09-30 18:55:21.921343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de000d1ff208'
down_revision = '17a6548abde5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.drop_column('Users', 'registered_at')
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('registered_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    # ### end Alembic commands ###
