"""add datetime to Bot table

Revision ID: 1e74bbac5a48
Revises: 0f7532be60ae
Create Date: 2023-09-29 00:11:11.896337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e74bbac5a48'
down_revision = '0f7532be60ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bots', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bots', 'created_at')
    # ### end Alembic commands ###
