"""add ChannelBotBundles db

Revision ID: 224244d30d47
Revises: 710f33c8368f
Create Date: 2023-05-13 14:59:54.613291

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "224244d30d47"
down_revision = "710f33c8368f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ChannelBotBundles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("bot_id", sa.INTEGER(), nullable=False),
        sa.Column("bundle", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "bots", "channels_count", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bots", "channels_count", existing_type=sa.INTEGER(), nullable=True)
    op.drop_table("ChannelBotBundles")
    # ### end Alembic commands ###
