"""add 'email' form to User

Revision ID: 37be991dd811
Revises: 16b3d5f8e31c
Create Date: 2023-09-30 17:15:22.930933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37be991dd811'
down_revision = '16b3d5f8e31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
