"""update ChanneBot

Revision ID: 6417171b537b
Revises: 954e45b68e8f
Create Date: 2023-09-21 20:30:33.893835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6417171b537b'
down_revision = '954e45b68e8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChannelBotBundles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.drop_column('ChannelBotBundles', 'date_parsed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChannelBotBundles', sa.Column('date_parsed', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ChannelBotBundles', 'created_at')
    # ### end Alembic commands ###
