"""create bots table

Revision ID: 90421e74de2b
Revises: 
Create Date: 2023-05-07 15:18:13.749342

"""
<<<<<<< HEAD
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

=======
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

>>>>>>> 5d8c2b0 (adding new version with tests and starlette-admin)
# revision identifiers, used by Alembic.
revision = "90421e74de2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bot_token", sa.String(), nullable=False),
        sa.Column("channels", postgresql.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
        sa.UniqueConstraint("bot_token"),
        sa.UniqueConstraint("description"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bots")
    # ### end Alembic commands ###
